_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 150

accelerator: cpu
devices: 1
num_sanity_val_steps: 2  # Run validation on a few batches before training

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
log_every_n_steps: 2
enable_checkpointing: true
enable_progress_bar: true
enable_model_summary: true
profiler: "simple"  # Options: simple, advanced, pytorch

# Debugging options
detect_anomaly: false  # Helps catch NaN issues early
val_check_interval: 1.0  # Check validation more frequently (every 1/4 epoch)

# Gradient clipping to prevent NaN issues
gradient_clip_val: 1.0
gradient_clip_algorithm: "norm"

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
