repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^(notebooks/|src/models/components/metrics/)
      - id: ruff-format
        exclude: ^(notebooks/|src/models/components/metrics/)

  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-summaries=88", "--wrap-descriptions=88"]
        exclude: ^(notebooks/|src/models/components/metrics/)


  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(notebooks/|src/models/components/metrics/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
        exclude: ^(notebooks/|src/models/components/metrics/)

default_language_version:
    python: python3
