default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0  # Use the latest version
    hooks:
      - id: ruff
      - id: ruff-format  # (Optional) Enables auto-formatting like Black
