_target_: "src.models.pigvae_auto_module.PLGraphAE"

graph_ae:
  _target_: "src.models.components.modules.GraphAE"
  hparams:
    input_size: 768
    num_heads: 4
    num_layers: 3
    emb_dim: 768
    vae: true
    dropout: 0.15
    encoder:
      graph_encoder_hidden_dim: ${model.graph_ae.hparams.input_size}
      num_node_features: 128
      num_edge_features: 0
      graph_encoder_num_heads: ${model.graph_ae.hparams.num_heads}
      graph_encoder_ppf_hidden_dim: ${multiply:${model.graph_ae.hparams.input_size},4}
      graph_encoder_num_layers: ${model.graph_ae.hparams.num_layers}
      emb_dim: ${model.graph_ae.hparams.emb_dim}
      dropout: ${model.graph_ae.hparams.dropout}
      grid_size: 6
      project: True

    decoder:
      graph_decoder_hidden_dim: ${model.graph_ae.hparams.input_size}
      graph_decoder_pos_emb_dim: ${model.graph_ae.hparams.input_size}
      graph_decoder_num_heads: ${model.graph_ae.hparams.num_heads}
      graph_decoder_ppf_hidden_dim: ${multiply:${model.graph_ae.hparams.input_size},4}
      graph_decoder_num_layers: ${model.graph_ae.hparams.num_layers}
      dropout: ${model.graph_ae.hparams.dropout}
      head_dim: ${divide:${model.graph_ae.hparams.input_size},${model.graph_ae.hparams.num_heads}}
      num_embeddings: 170
      num_node_features: 128
      num_edge_features: 0
      project: True
      grid_size: 6

    bottle_neck_encoder:
      graph_encoder_hidden_dim: ${model.graph_ae.hparams.input_size}
      emb_dim: ${model.graph_ae.hparams.emb_dim}
      vae: ${model.graph_ae.hparams.vae}
      activation: silu

    bottle_neck_decoder:
      emb_dim: ${model.graph_ae.hparams.emb_dim}
      graph_decoder_hidden_dim: ${model.graph_ae.hparams.input_size}
      num_nodes: 36

    property_predictor:
      emb_dim: ${model.graph_ae.hparams.emb_dim}
      property_predictor_hidden_dim: ${model.graph_ae.hparams.input_size}
      num_properties: 1

kld_alpha_scheduler:
  _target_: "src.models.components.schedulers.KLDAlphaScheduler"
  hparams:
    initial_alpha: 0.0
    final_alpha: 1.0
    mode: linear
    num_epochs: ${divide:${trainer.max_epochs},3}
    start_epoch: 1

critic:
  _target_: "src.models.components.model.Critic"
  hparams:
    kld_loss_scale: 0.05
    kld_free_bits: 0.0
    vae: ${model.graph_ae.hparams.vae}
    grid_size: 6
    huber_beta: 2.0
    alpha_scale: 1.0
    beta_scale: 0.1
    gamma_scale: 0.001

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0003
  weight_decay: 0.01

scheduler:
  batch_size: ${data.hparams.batch_size}
  type: cosine_warmup
  warmup: 0.05
  max_lr: 0.0003
  div_factor: 10
  final_div_factor: 100

compile: false
